### ISSUE TITLE
ios button shown on desktop browser?

### ISSUE THREAD

**Issue by mindbodyheart09** [no81no/jplist#114]
Greetings, in my case, there are too many controls in a small space on the page. How do I use ios button style when loading the panel, even on desktop browser? 

I tried to use inline style="display:block", etc. But it doesn't work,

thanks in advance,

Michael

**Comment by no81no** [comment]
Hi Michael,
You can achieve this using css:

```css
.jplist-panel{
	display: none;
}

.jplist-ios-button{
	display: block;
	float: left;
	height: 30px;
	line-height: 30px;
	text-align: center;
	padding: 0 15px;
	
	background: rgba(0, 0, 0, 0) linear-gradient(to bottom, #fff 0px, #efefef 100%) repeat scroll 0 0;
	
	border: 1px solid #dbdbdb;
	border-radius: 3px;
	box-sizing: border-box;
	
	box-shadow: 0 0 1px #fff;
	text-shadow: 1px 1px 1px #fff;
	
	color: #27252a;
	cursor: pointer;				
	
	font-size: 15px;				
}

.jplist-panel.jplist-ios-show{
	display: block;
}
```
