### ISSUE TITLE
Question regarding List, Grid and Thumbs View Control

### ISSUE THREAD

**Issue by Mandyli100** [no81no/jplist#218]
I am working on this List, Grid view control, have a question regarding the view "all" from the dropdown. The example is showing 5 items per row when I choose View ALL from the dropdown under Grid View, is there a way I can change it to 3 items per row when View ALL?

**Comment by no81no** [comment]
You can play with items CSS to define the number of items in the row. For example:
```css
.jplist-grid-view .list-item {
    width: 33%;
}
```
